### ISSUE TITLE
Cant Find Download Button

### ISSUE THREAD

**Issue by itsdefnotleon** [tormyvancool/OBS-STUDIO_Countdown#3]
I Can't Find The Download Button For This Software. Can You Help?

**Comment by tormyvancool** [comment]
Did you ever use GitHub?
![image](https://github.com/tormyvancool/OBS-STUDIO_Countdown/assets/32305535/23246e03-cce9-41f3-adf9-5ee5d429e2cb)

**Comment by tormyvancool** [comment]
This is not an issue .The user is not able to use GitHub
